# Generated by Django 5.0.6 on 2024-07-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('prId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('html_url', models.URLField(max_length=255)),
                ('base_html_url', models.URLField(max_length=255)),
                ('requesterName', models.CharField(blank=True, max_length=100)),
                ('requestedTime', models.DateTimeField(auto_now_add=True)),
                ('mergedTime', models.DateTimeField(auto_now_add=True)),
                ('prStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('repoName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('userName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(default='', max_length=255)),
                ('creatorName', models.CharField(default='', max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
