# Generated by Django 5.0.6 on 2024-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='requester_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='total_pull_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
