# Generated by Django 4.2.5 on 2024-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0002_pullrequest_requester_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='total_pull_requests',
            field=models.IntegerField(default=0),
        ),
    ]
