# Generated by Django 4.2.5 on 2024-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0004_pullrequest_pr_status_pullrequest_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='base_html_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
