# Generated by Django 4.2.5 on 2024-06-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0005_pullrequest_base_html_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='base_html_url',
            field=models.URLField(max_length=255),
        ),
    ]
