# Generated by Django 4.2.5 on 2024-06-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0006_alter_pullrequest_base_html_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='id',
            new_name='prId',
        ),
        migrations.RenameField(
            model_name='pullrequest',
            old_name='pr_status',
            new_name='prStatus',
        ),
        migrations.RenameField(
            model_name='pullrequest',
            old_name='repo',
            new_name='repoName',
        ),
        migrations.RenameField(
            model_name='pullrequest',
            old_name='created_at',
            new_name='requestedTime',
        ),
        migrations.RenameField(
            model_name='pullrequest',
            old_name='requester_name',
            new_name='requesterName',
        ),
    ]
