# Generated by Django 4.2.5 on 2024-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0007_rename_id_pullrequest_prid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(blank=True, max_length=255, null=True)),
                ('createName', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
