# Generated by Django 4.2.5 on 2024-06-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0008_repositories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositories',
            old_name='createName',
            new_name='createrName',
        ),
    ]
