# Generated by Django 4.2.5 on 2024-06-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0009_rename_createname_repositories_creatername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositories',
            old_name='createrName',
            new_name='creatorName',
        ),
    ]
