# Generated by Django 4.2.5 on 2024-06-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0010_rename_creatername_repositories_creatorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='creatorName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='repositories',
            name='repoName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
