# Generated by Django 4.2.5 on 2024-06-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0011_alter_repositories_creatorname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUSer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
    ]
