# Generated by Django 4.2.5 on 2024-07-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0013_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Points',
        ),
    ]
