# Generated by Django 4.2.5 on 2024-07-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repoapp', '0014_point_delete_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='username',
            new_name='userName',
        ),
    ]
